<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{2f04ebe4-1125-492e-a916-ba3146ea2bec}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter +1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>