
// ****************** ExampleModelClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "ExampleModelClassFactory.h"
#include "ExampleModelServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComExampleModel (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbExampleModel);


DEFINE_REPOSITORY_DRIVER(CExampleModelClassFactory, ExampleModel_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CExampleModelClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_ExampleModel,CID_EXAMPLEMODEL, SRVNAME_ExampleModel "!CTcComExampleModel", Create_CTcComExampleModel)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CExampleModelClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbExampleModel)

END_FUNC_MAP()

CExampleModelClassFactory::CExampleModelClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_ExampleModel)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ExampleModel));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ExampleModel));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CExampleModelClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			