// ****************** ExampleModelServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelServices__h_INCLUDED
#define _ExampleModelServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "ExampleModelVersion.h"
#define SRVNAME_ExampleModel "ExampleModel"

// TcCOM-ClassID of CTcComExampleModel: {9D61E7B3-A758-4A4D-992C-8BE03ACE0BE4}
const CTCID CID_EXAMPLEMODEL = {0x9D61E7B3, 0xA758, 0x4A4D, {0x99, 0x2C, 0x8B, 0xE0, 0x3A, 0xCE, 0x0B, 0xE4}};
// TcCOM-ClassID of CFbExampleModel: {0D628E29-7A20-A177-E18C-32E5B62D50C1}
const CTCID CID_FB_EXAMPLEMODEL = {0x0D628E29, 0x7A20, 0xA177, {0xE1, 0x8C, 0x32, 0xE5, 0xB6, 0x2D, 0x50, 0xC1}};


#ifndef ExampleModel_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_A0ACD81A_1CA9_8E27_FB8B_54B742111D65_INCLUDED_)
#define _TC_TYPE_A0ACD81A_1CA9_8E27_FB8B_54B742111D65_INCLUDED_
typedef struct _ExtU_ExampleModel_T
{
	double Input;
} ExtU_ExampleModel_T, *PExtU_ExampleModel_T;
#endif // !defined(_TC_TYPE_A0ACD81A_1CA9_8E27_FB8B_54B742111D65_INCLUDED_)

#if !defined(_TC_TYPE_E9C18042_DF09_7966_2B73_520758095357_INCLUDED_)
#define _TC_TYPE_E9C18042_DF09_7966_2B73_520758095357_INCLUDED_
typedef struct _ExtY_ExampleModel_T
{
	double Output;
} ExtY_ExampleModel_T, *PExtY_ExampleModel_T;
#endif // !defined(_TC_TYPE_E9C18042_DF09_7966_2B73_520758095357_INCLUDED_)

#if !defined(_TC_TYPE_92A0C9BF_466D_484C_41FE_E09D2E5194DD_INCLUDED_)
#define _TC_TYPE_92A0C9BF_466D_484C_41FE_E09D2E5194DD_INCLUDED_
typedef struct _B_ExampleModel_T
{
	double TransferFcn;
} B_ExampleModel_T, *PB_ExampleModel_T;
#endif // !defined(_TC_TYPE_92A0C9BF_466D_484C_41FE_E09D2E5194DD_INCLUDED_)

#if !defined(_TC_TYPE_CC93465B_32FB_8273_1564_78469E9554D4_INCLUDED_)
#define _TC_TYPE_CC93465B_32FB_8273_1564_78469E9554D4_INCLUDED_
typedef struct _X_ExampleModel_T
{
	double TransferFcn_CSTATE;
} X_ExampleModel_T, *PX_ExampleModel_T;
#endif // !defined(_TC_TYPE_CC93465B_32FB_8273_1564_78469E9554D4_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("CE84CCE2-D100-F5AF-453F-F72BF49FBB88", ITcExampleModel)



#endif // _ExampleModelServices__h_INCLUDED
