
// ****************** ExampleModelDrv.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "ExampleModelDrv.h"
#include "ExampleModelClassFactory.h"
#include "ExampleModelVersion.h"

DECLARE_GENERIC_DEVICE(ExampleModelDRV)
#undef DEVICE_MAIN

IOSTATUS CExampleModelDrv::OnLoad( )
{
	TRACE(_T("CExampleModelClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CExampleModelClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CExampleModelDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CExampleModelDrv::ExampleModel_GetVersion( )
{
	return(0);
}