
// ****************** ExampleModelDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelDrv__h_INCLUDED
#define _ExampleModelDrv__h_INCLUDED

#include "TcPch.h"

#define ExampleModelDRV_NAME			"ExampleModel"
#define ExampleModelDRV_Major			1
#define ExampleModelDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CExampleModelDrv

#include "ObjDriver.h"

class CExampleModelDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl ExampleModel_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( ExampleModelDRV)
	VxD_Service( ExampleModel_GetVersion		)
End_VxD_Service_Table


#endif // _ExampleModelDrv__h_INCLUDED