// ****************** ExampleModelInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelInternal__h_INCLUDED
#define _ExampleModelInternal__h_INCLUDED

#include "rtwtypes.h"
#include "ExampleModel.h"
#include "ExampleModel_private.h"
#include "ExampleModel_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// ExtU_ExampleModel_T
#ifndef _TC_TYPE_A0ACD81A_1CA9_8E27_FB8B_54B742111D65_INCLUDED_
#define _TC_TYPE_A0ACD81A_1CA9_8E27_FB8B_54B742111D65_INCLUDED_
#endif
TYPESIZE_VALIDATION(ExtU_ExampleModel_T,8);

// ExtY_ExampleModel_T
#ifndef _TC_TYPE_E9C18042_DF09_7966_2B73_520758095357_INCLUDED_
#define _TC_TYPE_E9C18042_DF09_7966_2B73_520758095357_INCLUDED_
#endif
TYPESIZE_VALIDATION(ExtY_ExampleModel_T,8);

// B_ExampleModel_T
#ifndef _TC_TYPE_92A0C9BF_466D_484C_41FE_E09D2E5194DD_INCLUDED_
#define _TC_TYPE_92A0C9BF_466D_484C_41FE_E09D2E5194DD_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_ExampleModel_T,8);

// X_ExampleModel_T
#ifndef _TC_TYPE_CC93465B_32FB_8273_1564_78469E9554D4_INCLUDED_
#define _TC_TYPE_CC93465B_32FB_8273_1564_78469E9554D4_INCLUDED_
#endif
TYPESIZE_VALIDATION(X_ExampleModel_T,8);

#endif // _ExampleModelInternal__h_INCLUDED