<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_map" Id="{a5d038bb-31a5-4c9a-a99a-31e10298b8be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_map : REAL
VAR_INPUT
	// input variables
	fValue : REAL; // 16000
	fInMin : REAL; // 0
	fInMax : REAL; // 32767
	fOutMin: REAL; // 100
	fOutMax: REAL; // 0
END_VAR
VAR
	// internal variables
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// map fValue linearly from [fInMin, fInMAx] to [fOutMin, fOutMax]

F_map := fOutMin + (fValue - fInMin)*(fOutMax-fOutMin)/(fInMax-fInMin);]]></ST>
    </Implementation>
    <LineIds Name="F_map">
      <LineId Id="7" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>