
// ****************** ExampleModelCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelCtrl__h_INCLUDED
#define _ExampleModelCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CExampleModelDrvName "ExampleModel"

#include "ExampleModelW32Resource.h"
#include "ExampleModelW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "ExampleModelClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CExampleModelCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CExampleModelCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CExampleModelCtrl, CExampleModelClassFactory>
{
public:
	CExampleModelCtrl() : ITcOCFCtrlImpl<CExampleModelCtrl, CExampleModelClassFactory>(){}

	virtual ~CExampleModelCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_ExampleModelCtrl)
DECLARE_NOT_AGGREGATABLE(CExampleModelCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CExampleModelCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _ExampleModelCtrl__h_INCLUDED