// ****************** ExampleModelInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelInterfaces__h_INCLUDED
#define _ExampleModelInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ExampleModelServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_CE84CCE2_D100_F5AF_453F_F72BF49FBB88_INCLUDED_)
#define _TC_TYPE_CE84CCE2_D100_F5AF_453F_F72BF49FBB88_INCLUDED_
struct __declspec(novtable) ITcExampleModel : ITcUnknown 
{
	virtual HRESULT TCOMAPI ExampleModel_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcExampleModel, IID_ITcExampleModel);
#endif // !defined(_TC_TYPE_CE84CCE2_D100_F5AF_453F_F72BF49FBB88_INCLUDED_)



#endif // _ExampleModelInterfaces__h_INCLUDED
