
// ****************** ExampleModelW32Resource.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelW32Resource__h_INCLUDED
#define _ExampleModelW32Resource__h_INCLUDED

//#define IDS_ModuleClass					100
#define IDR_ExampleModelCtrl			101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif // APSTUDIO_READONLY_SYMBOLS
#endif // APSTUDIO_INVOKED

#endif // _ExampleModelW32Resource__h_INCLUDED
