// ****************** ExampleModelDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExampleModelDuts__h_INCLUDED
#define _ExampleModelDuts__h_INCLUDED
#include "ExampleModelServices.h"

#if defined(_X86_)
typedef struct _ST_FB_Main_FB_ExampleModel
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_Main_FB_ExampleModel, *PST_FB_Main_FB_ExampleModel;
#elif defined(_X64_)
typedef struct _ST_FB_Main_FB_ExampleModel
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_Main_FB_ExampleModel, *PST_FB_Main_FB_ExampleModel;
#endif

#if defined(_X86_)
typedef struct _ST_FB_exit_FB_ExampleModel
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_exit_FB_ExampleModel, *PST_FB_exit_FB_ExampleModel;
#elif defined(_X64_)
typedef struct _ST_FB_exit_FB_ExampleModel
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_exit_FB_ExampleModel, *PST_FB_exit_FB_ExampleModel;
#endif

#if defined(_X86_)
typedef struct _ST_FB_init_FB_ExampleModel
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1;
} ST_FB_init_FB_ExampleModel, *PST_FB_init_FB_ExampleModel;
#elif defined(_X64_)
typedef struct _ST_FB_init_FB_ExampleModel
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[5];
} ST_FB_init_FB_ExampleModel, *PST_FB_init_FB_ExampleModel;
#endif



#endif // _ExampleModelDuts__h_INCLUDED
