
// ****************** ExampleModelCtrl.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "ExampleModelW32.h"
#include "ExampleModelCtrl.h"