
// ****************** FbExampleModel.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "FbExampleModel.h"

#include "ExampleModel.h"

#include "ObjClassFactory.h"
using namespace TcMgSdk;

///////////////////////////////////////////////////////////////////////////////
// Definitions
///////////////////////////////////////////////////////////////////////////////
#ifdef _DEBUG
#define new DEBUG_NEW
#endif
#if TC_BUILD<=4024
DEFINE_THIS_FILE()
#endif

///////////////////////////////////////////////////////////////////////////////
// CFbExampleModel specific globals
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CFbExampleModel static members
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CFbExampleModel implementation
///////////////////////////////////////////////////////////////////////////////
CFbExampleModel::CFbExampleModel()
{
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_CallerExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_CallerExceptions;


	
}

CFbExampleModel::~CFbExampleModel()
{

}

bool CFbExampleModel::FB_Main()
{

	bool fbMainResult = true;

	

	auto fpState = FpControl(FpCtrlSection::Update);
	((RT_MODEL_ExampleModel_T*)PExampleModel_M)->inputs->Input = Input;
	::ExampleModel_step(((RT_MODEL_ExampleModel_T*)PExampleModel_M));
	Output = ((RT_MODEL_ExampleModel_T*)PExampleModel_M)->outputs->Output;

	FpRestore(fpState);


	return fbMainResult;
}

void CFbExampleModel::_FB_Main(ST_FB_Main_FB_ExampleModel* ST_Param)
{
	ST_Param->result = ((CFbExampleModel*)ST_Param->pInst)->FB_Main(  );
}

bool CFbExampleModel::FB_exit(bool bInCopyCode)
{

	bool fbExitResult = true;

	auto fpState = FpControl(FpCtrlSection::Init);
	if (((RT_MODEL_ExampleModel_T*)PExampleModel_M)!=NULL)
	{
		::ExampleModel_terminate(((RT_MODEL_ExampleModel_T*)PExampleModel_M));
		PExampleModel_M = NULL;
	}

	FpRestore(fpState);


	SingleInstanceRelease();
	__super::Exit(bInCopyCode);

	return fbExitResult;
}

void CFbExampleModel::_FB_exit(ST_FB_exit_FB_ExampleModel* ST_Param)
{
	ST_Param->result = ((CFbExampleModel*)ST_Param->pInst)->FB_exit( ST_Param->bInCopyCode );
}

bool CFbExampleModel::FB_init(bool bInitRetains, bool bInCopyCode)
{

	bool fbInitResult = true;

	if(fbInitResult)
	{
		PExampleModel_M = ::ExampleModel();

		m_pData = nullptr;
		fbInitResult = __super::Init(0,TC_BUILD_MIN,bInitRetains,bInCopyCode);
		if (!fbInitResult)
		{
			error("__super::Init() did not succeed");
		}
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_CallerExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_CallerExceptions;


	}

	fbInitResult &= SingleInstanceLock(GUID_NULL);
	if(fbInitResult)
	{
		auto fpState = FpControl(FpCtrlSection::Init);
		::ExampleModel_initialize(((RT_MODEL_ExampleModel_T*)PExampleModel_M));

		FpRestore(fpState);
	}
	else
	{
		error("SingleInstanceLock() did not succeed");
	}

	return fbInitResult;
}

void CFbExampleModel::_FB_init(ST_FB_init_FB_ExampleModel* ST_Param)
{
	ST_Param->result = ((CFbExampleModel*)ST_Param->pInst)->FB_init( ST_Param->bInitRetains, ST_Param->bInCopyCode );
}




BEGIN_FUNC_MAP_FB(CFbExampleModel)
	FUNC_ENTRY_LIB(VID_ExampleModel, CID_FB_EXAMPLEMODEL , "FB_ExampleModel" "__main", CFbExampleModel::_FB_Main)
FUNC_METHOD_ENTRY_LIB(VID_ExampleModel,CID_FB_EXAMPLEMODEL , "FB_EXIT", "FB_ExampleModel" "__FB_exit", CFbExampleModel::_FB_exit)
FUNC_METHOD_ENTRY_LIB(VID_ExampleModel,CID_FB_EXAMPLEMODEL , "FB_INIT", "FB_ExampleModel" "__FB_init", CFbExampleModel::_FB_init)

END_FUNC_MAP_FB()

DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbExampleModel)
{
	return CFbExampleModel::TcHandleFuncMap(mode, idx, idxcounter, pFncId, pipFnc, ppMethod, ppName, pSignature, pVersion);
}
