
// ****************** FbExampleModel.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbExampleModel__h_INCLUDED
#define _FbExampleModel__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "ExampleModelInternal.h"

#include "ExampleModelDuts.h"
#include "ExampleModelInterfaces.h"
#include "ExampleModelVersion.h"

class CFbExampleModel :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_ExampleModel;}
	inline CLSID get_ClassID() {return CID_FB_EXAMPLEMODEL;}

	DECLARE_FUNC_MAP_FB()

	CFbExampleModel();
	~CFbExampleModel();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_ExampleModel* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_ExampleModel* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_ExampleModel* ST_Param);


	double Input;
	double Output;
	PVOID PExampleModel_M;


};
TYPESIZE_VALIDATION2(CFbExampleModel,32,40);

			
#endif // _FbExampleModel__h_INCLUDED
			