// ****************** TcComExampleModel.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.2.1.4
// MATLAB 9.9.0.1718557 (R2020b) Update 6 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.2.1.4
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _TcComExampleModel__h_INCLUDED
#define _TcComExampleModel__h_INCLUDED


#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcMatSimTcCom.h"
#include "ExampleModelInternal.h"

#include "ExampleModelInterfaces.h"
#include "ExampleModelVersion.h"


class CTcComExampleModel :
	public TcMatSim::GeneratedTcCom,
	public ITcWatchSource,
	public ITcCyclic,
	public ITcPostCyclic,
	public ITcADI,
	public ITcExampleModel
{
public:
	DECLARE_IUNKNOWN_DERIVED()
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_PARA()
	DECLARE_ITCADI()
	DECLARE_IPERSIST_LIB()


	// Constructor
	CTcComExampleModel();

	// Destructor
	~CTcComExampleModel();

	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT Update(ITcTask* ipTask, ULONG_PTR context);
	HRESULT CheckAndAdaptCycleTimes();

	// ITcExampleModel
	HRESULT TCOMAPI ExampleModel_step();



	RT_MODEL_ExampleModel_T* PExampleModel_M;



};
			

#endif // _TcComExampleModel__h_INCLUDED